import { CommissionRule } from "./types";

export const IVA_RATE = 0.19; // 19% standard in Chile

export const EXPENSE_CATEGORIES = [
  'arriendo',
  'servicios básicos',
  'marketing',
  'software',
  'insumos',
  'operación',
] as const;

export const DEFAULT_PROFESSIONALS = [
  'Ivanova',
  'Jenny',
  'Darling'
];

export const DEFAULT_COMMISSION_RULES: Record<string, CommissionRule> = {
  "Extension adhesivas": { type: 'fixed', value: 500 },
  "Adhesiva Invisible Premium Corta": { type: 'fixed', value: 500 },
  "Adhesiva Invisible Premium larga": { type: 'fixed', value: 500 },
  "Topper Malla Invisible": { type: 'fixed', value: 10000 },
  "Chasquilla": { type: 'fixed', value: 10000 },
  "Cortina Lisa": { type: 'fixed', value: 10000 },
  "Cortina Curly": { type: 'fixed', value: 10000 },
  "Protesis": { type: 'fixed', value: 30000 },
  "Nano Keratina": { type: 'fixed', value: 500 },
  "Removedor Líquido": { type: 'fixed', value: 500 },
  "PROTESIS CAPILAR + INSTALACION + CORTE": { type: 'percentage', value: 50 },
  "LAVADO + SECADO": { type: 'percentage', value: 40 },
  "TINTURA MUJER": { type: 'percentage', value: 30 },
  "MECHAS": { type: 'percentage', value: 30 },
  "DECOLORACION GLOBAL": { type: 'percentage', value: 30 },
  "COLOR CRECIMIENTO RAIZ": { type: 'percentage', value: 30 },
  "BAÑO DE COLOR": { type: 'percentage', value: 30 },
  "BALAYAGE": { type: 'percentage', value: 30 },
  "BABYLIGHTS": { type: 'percentage', value: 30 },
  "MANTENCION TOPPERS": { type: 'percentage', value: 40 },
  "MANTENCIÓN EXTENSION CORTINA": { type: 'percentage', value: 30 },
  "RETIRO EXTENSION ADHESIVA": { type: 'percentage', value: 30 },
  "MANTENCION PROTESIS CAPILAR": { type: 'percentage', value: 50 },
  "MANTENCIÓN DE EXTENSION ADHESIVA": { type: 'percentage', value: 30 },
  "HIDRATACION CAPILAR": { type: 'percentage', value: 30 },
  "MASAJE CAPILAR": { type: 'percentage', value: 30 },
  "BOTOX CAPILAR": { type: 'percentage', value: 30 },
  "RESTAURACIÓN CAPILAR BRAE": { type: 'percentage', value: 50 },
  "REPARACION OLAPLEX": { type: 'percentage', value: 30 },
  "TOPPER + INSTALACIÓN + PEINADO": { type: 'percentage', value: 50 },
  "PROTESIS + INSTALACIÓN + PEINADO": { type: 'percentage', value: 50 },
  "EXTENSION + INSTALACIÓN + PEINADO": { type: 'percentage', value: 50 },
  "BRUSHING": { type: 'percentage', value: 50 },
  "CORTE DE PUNTAS": { type: 'percentage', value: 50 },
  "CORTE DEGRADADO": { type: 'percentage', value: 50 },
  "CORTE + BARBA + LAVADO": { type: 'percentage', value: 50 },
  "ALISADO SIN FORMOL": { type: 'percentage', value: 30 }
};

export const DEFAULT_SERVICE_PRICES: Record<string, { price: number, cost?: number, category: string, type: string }> = {
  "PROTESIS CAPILAR + INSTALACION + CORTE - From": { price: 0, cost: 0, category: "PROTESIS", type: "Corte de pelo para mujer" },
  "LAVADO + SECADO": { price: 13990, cost: 0, category: "LAVADOS", type: "Secado con secadora" },
  "TINTURA MUJER - From": { price: 39990, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Tinte" },
  "MECHAS - From": { price: 80000, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Tinte" },
  "DECOLORACION GLOBAL - From": { price: 140000, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Tinte" },
  "COLOR CRECIMIENTO RAIZ - From": { price: 39990, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Tinte" },
  "BAÑO DE COLOR - From": { price: 39990, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Tinte" },
  "BALAYAGE - From": { price: 120000, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Mechas balayage" },
  "BABYLIGHTS - From": { price: 110000, cost: 0, category: "TINTURA, DECOLORACION Y COLOR", type: "Mechas" },
  "MANTENCION TOPPERS - From": { price: 39990, cost: 0, category: "MANTENCIONES", type: "Rastas" },
  "MANTENCIÓN EXTENSION CORTINA - From": { price: 25000, cost: 0, category: "MANTENCIONES", type: "Extensiones de cabello" },
  "RETIRO EXTENSION ADHESIVA": { price: 2500, cost: 0, category: "MANTENCIONES", type: "Extensiones de uñas de gel" },
  "MANTENCION PROTESIS CAPILAR - From": { price: 39990, cost: 0, category: "MANTENCIONES", type: "Extensiones de cabello" },
  "MANTENCIÓN DE EXTENSION ADHESIVA": { price: 4000, cost: 0, category: "MANTENCIONES", type: "Extensiones de cabello" },
  "HIDRATACION CAPILAR - From": { price: 59990, cost: 0, category: "HIDRATACIONES", type: "Corte de pelo para mujer" },
  "MASAJE CAPILAR - From": { price: 39990, cost: 0, category: "HIDRATACIONES", type: "Masaje craneal" },
  "BOTOX CAPILAR - From": { price: 59990, cost: 0, category: "HIDRATACIONES", type: "Tratamiento capilar" },
  "RESTAURACIÓN CAPILAR BRAE - From": { price: 59990, cost: 0, category: "HIDRATACIONES", type: "Tratamiento para la pérdida de cabello" },
  "REPARACION OLAPLEX - From": { price: 59990, cost: 0, category: "HIDRATACIONES", type: "Tratamiento capilar" },
  "TOPPER + INSTALACIÓN + PEINADO - From": { price: 0, cost: 0, category: "EXTENSIONES Y PROTESIS", type: "Extensiones de cabello" },
  "PROTESIS + INSTALACIÓN + PEINADO": { price: 0, cost: 0, category: "EXTENSIONES Y PROTESIS", type: "Extensiones de cabello" },
  "EXTENSION + INSTALACIÓN + PEINADO": { price: 0, cost: 0, category: "EXTENSIONES Y PROTESIS", type: "Extensiones de cabello" },
  "BRUSHING - From": { price: 14000, cost: 0, category: "CORTE DE PELO MUJER", type: "Corte de pelo para mujer" },
  "CORTE DE PUNTAS": { price: 12990, cost: 0, category: "CORTE DE PELO MUJER", type: "Corte de pelo para mujer" },
  "CORTE DEGRADADO": { price: 12000, cost: 0, category: "CORTE DE PELO HOMBRE", type: "Corte de pelo para hombre" },
  "CORTE + BARBA + LAVADO": { price: 17990, cost: 0, category: "CORTE DE PELO HOMBRE", type: "Corte de pelo para hombre" },
  "ALISADO SIN FORMOL - From": { price: 59990, cost: 0, category: "ALISADOS", type: "Alisado permanente" },
  // New Products
  "Extension adhesivas #1": { price: 8500, cost: 1500, category: "ADHESIVA ESTANDAR", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #1": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #1b": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #2": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #4": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #6": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #p1b/6/t1b": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #p4/27/t4": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #p6/613/t4": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #27": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #p18/613": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #p27/613": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #t2/60": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium Corta #613": { price: 8999, cost: 2850, category: "ADHESIVA INVISIBLES PREMIUM CORTA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #p4/27/t4": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #p6/613/t4": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #p8/60": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #p18/613": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #t2/60": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #27": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #p27/613": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Adhesiva Invisible Premium larga #60": { price: 12000, cost: 5500, category: "ADHESIVA INVISIBLES PREMIUM LARGA", type: "Extensiones" },
  "Topper Malla Invisible #R6/22/6": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #2": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #4": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "topper Malla Invisible #M6/22": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #R18-613/18": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #613/bc": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #10/6": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Topper Malla Invisible #613/10/4": { price: 219990, cost: 50000, category: "TOPPER MALLA INVISIBLE", type: "Topper" },
  "Chasquilla #Natural Black": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Brown Black": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #613": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Dark Brown": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Light Brown": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Brown": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Ash Brown": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Chasquilla #Blonde": { price: 49990, cost: 10000, category: "CHASQUILLAS", type: "Chasquilla" },
  "Cortina Lisa #2": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #Natural Black": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #1b": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #613": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #8": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #7": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Cortina Lisa #4": { price: 119990, cost: 30000, category: "CORTINAS LISA", type: "Cortina" },
  "Shampoo ESSENTIAL": { price: 25990, cost: 19509, category: "INSUMOS", type: "Producto" },
  "Cortina Curly #Natural Black": { price: 149990, cost: 78000, category: "CORTINA CURLY", type: "Cortina" },
  "Acondicionador ESSENTIAL": { price: 29920, cost: 17811, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR HAIR MASK  ESSENTIAL": { price: 35300, cost: 26494, category: "INSUMOS", type: "Producto" },
  "ACEITE BLEND ACONDICIONADOR": { price: 30990, cost: 23243, category: "INSUMOS", type: "Producto" },
  "SPRAY FINISHING ESSNTIAL": { price: 43400, cost: 32516, category: "INSUMOS", type: "Producto" },
  "SHAMPOO REVIVAL": { price: 26100, cost: 19509, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR REVIVAL": { price: 28300, cost: 21195, category: "INSUMOS", type: "Producto" },
  "MASCARILLA RECONSTRUCTIVA REVIVAL": { price: 35400, cost: 26494, category: "INSUMOS", type: "Producto" },
  "ACEITE REVIVAL GORGEOUS  SHINE ACONDICIONADOR": { price: 30990, cost: 23243, category: "INSUMOS", type: "Producto" },
  "AMPOLLA REVIVAL POWER DOSE CONDITIONING": { price: 9490, cost: 7035, category: "INSUMOS", type: "Producto" },
  "KIT TRAVEL REVIVAL": { price: 45990, cost: 34202, category: "INSUMOS", type: "Producto" },
  "SHAMPOO ANTI-FRIZZ DIVINE": { price: 26000, cost: 19509, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR ANTI-FRIZZ DIVINE": { price: 28300, cost: 21195, category: "INSUMOS", type: "Producto" },
  "MASCARILLA ACONDICIONADORA DIVINE LIQUID": { price: 26990, cost: 20232, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR 10 EN 1 LEAVE-IN DIVINE": { price: 40200, cost: 30107, category: "INSUMOS", type: "Producto" },
  "SERUM DIVINE PLUME": { price: 37100, cost: 27819, category: "INSUMOS", type: "Producto" },
  "AMPOLLA BOND ANGEL POWER DOSE": { price: 9490, cost: 7035, category: "INSUMOS", type: "Producto" },
  "KIT BOND ANGEL PROTECTIVE RECONSTRUCTIVO PASO 1 Y 2": { price: 67800, cost: 50821, category: "INSUMOS", type: "Producto" },
  "FORTIFICADOR PASO 3 BOND ANGEL": { price: 25700, cost: 19263, category: "INSUMOS", type: "Producto" },
  "SHAMPOO BLOND REPAIR": { price: 26600, cost: 19509, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR BLOND REPAIR": { price: 28300, cost: 21195, category: "INSUMOS", type: "Producto" },
  "MASCARILLA BLOND REPAIR ACONDICIONADORA": { price: 35400, cost: 26494, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR BLOND REPAIR LEVEL-IN": { price: 43990, cost: 32997, category: "INSUMOS", type: "Producto" },
  "SHAMPOO SOUL COLOR": { price: 27600, cost: 20714, category: "INSUMOS", type: "Producto" },
  "ACONDICIONADOR SOUL": { price: 29900, cost: 22400, category: "INSUMOS", type: "Producto" },
  "MASCARILLA HAIR ESSENTIAL REPARACION INTENSA": { price: 35300, cost: 26494, category: "INSUMOS", type: "Producto" },
  "BLOND POWDER PASO 2 BOND ANGEL": { price: 33900, cost: 25410, category: "INSUMOS", type: "Producto" },
  "MASCARILLA ACONDICIONADORA SOUL": { price: 34400, cost: 25772, category: "INSUMOS", type: "Producto" },
  "Protesis Tono #1": { price: 289990, cost: 75000, category: "PROTESIS CAPILARES", type: "Protesis" },
  "Protesis Tono #2": { price: 289990, cost: 75000, category: "PROTESIS CAPILARES", type: "Protesis" },
  "Protesis Tono #3": { price: 289990, cost: 75000, category: "PROTESIS CAPILARES", type: "Protesis" },
  "Protesis Tono #1b": { price: 289990, cost: 75000, category: "PROTESIS CAPILARES", type: "Protesis" },
  "Protesis cana Tono #1b/20": { price: 479990, cost: 75000, category: "PROTESIS CAPILAR CANAS", type: "Protesis" },
  "Protesis cana Tono #1b/50": { price: 479990, cost: 75000, category: "PROTESIS CAPILAR CANAS", type: "Protesis" },
  "Protesis cana Tono #1b/65": { price: 479990, cost: 75000, category: "PROTESIS CAPILAR CANAS", type: "Protesis" },
  "Protesis Premium 4k Tono #1": { price: 489990, cost: 75000, category: "PROTESIS CAPILAR PREMIUM", type: "Protesis" },
  "Protesis Premium 4k Tono #1b": { price: 489990, cost: 75000, category: "PROTESIS CAPILAR PREMIUM", type: "Protesis" },
  "Protesis Premium 4k Tono #2": { price: 489990, cost: 75000, category: "PROTESIS CAPILAR PREMIUM", type: "Protesis" },
  "Nano Keratina Premium Dubai #1b": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #2": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #3": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #4": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #7": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #8": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #10": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #27": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #613": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Nano Keratina Premium Dubai #1b/613": { price: 5500, cost: 650, category: "NANO KERATINA PREMIUM", type: "Extensiones" },
  "Ultra Hold – Cinta Adhesiva Doble Cara 3 Yardas (1/2 pulgada)": { price: 19990, cost: 2000, category: "INSUMOS EXTENSIONES & PROTESIS", type: "Insumo" },
  "Removedor Líquido para Cinta de Extensiones 118ml": { price: 19990, cost: 2500, category: "INSUMOS EXTENSIONES & PROTESIS", type: "Insumo" }
};
